### ISSUE TITLE
Add camera calibration steps to pre-experiment checklist

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_experiments#169]
Related to #168, #107 and #78, we need to develop a reproducible pre-experiment checklist for quality control of camera image. This should allow us to control for illumination, focus, gain, filter, lens, and sensor changes to minimize unexpected divergence in quality for a known calibration target.

As a first protocol, we will use the laminated rigid checkerboard already used for intrinsic camera calibration (see [Calibration Targets](https://github.com/SainsburyWellcomeCentre/aeon_experiments/tree/4fba4d8fb6fda89587e27e3ca352fec59c8cbeec#calibration-targets)). For this issue to be resolved, the README should be updated to include camera quality checks. For this, we need to resolve the following:

- [ ] Decide standard positions for calibration targets to maximize arena coverage
- [ ] Decide calibration data format:
  - [ ] Illumination parameters:
    - [ ] Type of light source (e.g. LED, spotlight)
    - [ ] Make and model
    - [ ] Power supply parameters
    - [ ] Number of bars / spotlights
    - [ ] Spatial distribution (top, ring-light, scattered pointing up, etc)
  - [ ] Lens parameters (make and model)
  - [ ] For each camera:
    - [ ] Make and model
    - [ ] Sensor model
    - [ ] Acquisition parameters (gain, binning, exposure, etc)
    - [ ] Rough spatial location (overview, side, quadrant, etc, also see [#154](https://github.com/SainsburyWellcomeCentre/aeon_experiments/issues/154))
    - [ ] Segmentation mask (optional)
  - [ ] IR Filter parameters (make and model, spectral response, efficiency, etc)
- [ ] Decide version control mechanism (dataset vs aeon_experiments git repo)
- [ ] Update calibration workflow to record both pre- and post-calibration screenshots
- [ ] Develop set of reproducible analysis scripts for benchmarking image quality
- [ ] Checks for streaming from all camera devices
