### ISSUE TITLE
FLIR Thermal Camera Demo Checklist

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#28]
I think we should come up with a checklist of things we want to do/see when FLIR comes for the on-site demo on the 20th.

- [x] Compared shaved and unshaved mice
- [x] See if shaving is ok with NRF and given Tiago's PPL
- [x] See if FLIR guys are allowed in animal room and what prereqs they need to fulfill (e.g. mask-fit test)
