### ISSUE TITLE
Integrate multi-animal tracking acquisition workflow

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_experiments#297]
- [x] #242 
- [x] #241
- [x] https://github.com/SainsburyWellcomeCentre/aeon_mecha/pull/206
~- [ ] #156~
- [x] Specify video collection and pipeline for training multi-animal tracking model
- [x] Add SLEAP nodes to full social workflow #218
