### ISSUE TITLE
Checklist before starting next cohort of social mice

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_experiments#406]
AEON3 and AEON4
- [x] Change task logic to meet new requirements. See issue #404 
- [x] Change bonsai GUI  See issue #391
- [x] Write data visualizer to 1) look at data from current cohort to see if there are values to tweak. 2)look on a daily basis to data of new cohort. #404 
  - [x] Add rfid viz
- [x] Update firmware on all patch beambreaks
- [x] Update firmware on all rfids #425 
- [x] Check Lux

AEON3
- [x] Check side cameras: they are all different from each other and few not focused. Important now for MoSeq.
- [x] Train and check multianimal model.
- [x] Mouse seems to be very biased against patch 2. Check if there is anything strange there.
- [x] Measure Torque

AEON4
- [x] Check side cameras: they are all different from each other and few not focused.
- [x] Train and check multianimal model.
- [x] Add RFID readers
- [x] Replace/fix patch with the broken connector and patch 2 #402 .
- [x] Measure Torque
- [x] #444
     -add flir camera to be used as webcam for now, pointing at the ceiling.

**Comment by jkbhagatio** [comment]
Closing this as done.
