### ISSUE TITLE
System (failure) tests for experiment 0 iterations

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#58]
Related to SainsburyWellcomeCentre/aeon_experiments#73 , we should keep a list of system failures we want to explicitly test and handle. I think this list can include both software and hardware issues. @Dario55 @glopesdev please add to this:

- [ ] Power outage (#29)
- [x] Disk space full (#24)
- [ ] Device replacements (#53)
- [x] Software crashes (#31)
- [x] Feeding system issues (#32)
- [x] Network failures (#50)
- [ ] Check camera triggers (once in experiment 0 interval between triggers was < 8 ms) (#49)
